### ISSUE TITLE
Implement javax.cache

### ISSUE THREAD

**Issue by andyjefferson** [Cetsoft/imcache#1]
Please base your cache around javax.cache (which is pretty close to final now). That way many projects will be able to use your cache immediately without having to code to a proprietary API.

**Comment by ben-manes** [comment]
I'd recommend skipping JCache as I am very disappointed with the specification. Based on a similar request, I implemented an adapter for my Java 8 rewrite of ConcurrentLinkedHashMap & Guava's cache, [Caffeine](https://github.com/ben-manes/caffeine). I have no polite way to express my opinion of the proposed standard.

(I just discovered this project, nifty!)

**Comment by AdoHe** [comment]
@ben-manes Thanks :)

**Comment by andyjefferson** [comment]
So one user is disappointed with the javax.cache spec? @ben-manes did you feed back any concerns about that spec to the group who generated that spec? After all they had their discussions in the open with input from many people, and provided with guidance from the original leads of EHCache, Coherence, etc. 

Simple fact is that for "imcache" to be easily adopted it could provide an implementation of javax.cache ALONGSIDE whatever other API it wants to provide. It isn't an "either"/"or" decision.

**Comment by ben-manes** [comment]
I was invited to join the JSR when it was relaunched, but unable to and not allowed to communicate with members due to the Oracle-Google lawsuit. 

I provided them a shallow [critique](https://docs.google.com/document/d/1vPsKYoeVftVkH9TbkV3g9lAnslAQtUQyV8ZZ79PQI6M/edit?usp=docslist_api) covering API flaws. It does not attempt to describe alternative APIs. To their credit, my strong disfavor of their decision to break the API in a minor release (to add async support) led to that change targeting a major version release instead.

**Comment by andyjefferson** [comment]
@ben-manes, thanks for the info, some very good points. I also have had problems with JSRs (and Oracle) in the past so can only empathise.

**Comment by yusufaytas** [comment]
As most of the people agreed on skipping JCache, we won't support it in the next releases.
